name: GH App- Run Semgrep Scan on Dispatch

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [zcs-event]

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ vars.GH_APP_CLONE_REPO_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_CLONE_REPO_PRIVATE_KEY }}      
      
      - name: Checkout different repo ${{ github.event.client_payload.repository_name }}
        uses: actions/checkout@v2
        with:
          repository:  ${{ github.event.client_payload.repository_full_name }}   
          token: ${{ steps.get_workflow_token.outputs.token }}
          
      - name: Run Semgrep Scan
        run: |
          export SEMGREP_REPO_NAME=$SEMGREP_REPO_NAME
          export SEMGREP_REPO_URL=$GIT_URL
          export SEMGREP_BRANCH=$SEMGREP_BRANCH
          semgrep ci
        env:
          GIT_URL: ${{ github.event.client_payload.git_url }}
          REPOSITORY_NAME: ${{ github.event.client_payload.repository_name }}
          SEMGREP_REPO_URL: ${{ github.event.client_payload.git_url }}
          SEMGREP_REPO_NAME: ${{ github.event.client_payload.repository_full_name }}
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          SEMGREP_BRANCH: ${{ github.event.client_payload.repository_default_branch }}
